import Head from 'next/head';
import Image from 'next/image';
import clsx from 'clsx';
import axios from 'axios';
import styles from './Home.module.scss';



export default function Home({ meals }) {

	// console.log(props)
	// console.log(meals)
	const newMeals = meals.slice(0, 6);


	return (
		<>
			<Head>
				<title>Next Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={clsx(styles.main)}>
				<figure className="vusual">
					<article className='bg'>
						{newMeals.map(item => (
							<div className="pic" key={item.idMeal} style={{ position:'relative', width: 400, height: 300 }}>
								<Image 
									src={item.strMealThumb} 
									alt={item.strMeal} 
									priority 
									fill 
									quality={50} 
								/>
							</div>
						))}
					</article>
					<article className='list'>
						{newMeals.map(item => (
							<h2 key={item.idMeal}>{item.strMeal}</h2>
						))}
					</article>
				</figure>
			</main>
		</>
	);
}


export async function getStaticProps() {
	const res = await axios.get('https://www.themealdb.com/api/json/v1/1/filter.php?c=Seafood');
	const data = res.data;
	return {
		props: data, //data json을 넘겨야됨
		revalidate: 10, //SSG 10s
	}
}